### ISSUE TITLE
Memory leak on verison 0.24

### ISSUE THREAD

**Issue by pyves007** [ConSol-Monitoring/snclient#122]
Hello, after have tested the version 0.24.0 since the 27th May, it seems that there is steal some memory leaks. 
![image](https://github.com/ConSol-Monitoring/snclient/assets/58570757/26e266ff-95b4-4db8-9a0b-58e1b7286c73)
I could imagine that we are not alone with this issue. Have a nice day, Py

**Comment by sni** [comment]
so far, i cannot see any memory issues with the 0.24 on any of the systems i have control of.
What are you plotting there? And maybe add some information about which os that is or so?

**Comment by FranckSallet** [comment]
hello

I confirm that the memory leak is still present
I saw it on Windows Server 2016 and 2019
I have a suspicion about "wrapped scripts"...

before:
![memory_snclient1](https://github.com/ConSol-Monitoring/snclient/assets/132520562/6b457b7a-2d54-45c9-b918-a7c3de1dd659)

after:
![memory_snclient2](https://github.com/ConSol-Monitoring/snclient/assets/132520562/b0681dad-3910-4a40-a1d7-1eb244e18bd6)

**Comment by lgmu** [comment]
@pyves007 @FranckSallet we just released 0.25 - it reduces memory usage overall. Could you please give us feedback with that version?

**Comment by pyves007** [comment]
Thank you, i'll test it.

**Comment by lgmu** [comment]
I installed it on a windows server 2019 on friday and didn't notice anything regarding memory usage over the weekend.
If you still have this issue, please attach your config and let us know which features you use.

**Comment by FranckSallet** [comment]
Hi

memory leak is still present in version 0.25
I notice that the memory issue seems not to be present when using just the builtin check command.
Snclient's memory increases each time an "external script" is used.

Regards

**Comment by lgmu** [comment]
Hi,
thanks for your feedback. I could see a slight increase in memory usage when executing ps1 Scripts. 
Are you also running ps1 scripts or something else?

**Comment by FranckSallet** [comment]
yes, mainly powershell scripts

**Comment by lgmu** [comment]
I've tested this with 1000 executions of a ps1 script, but the memory only increased from 12 to around 16MB. 
How long do your powershell scripts run? Could you check if a particular one causes this?

**Comment by sni** [comment]
i cannot reproduce it either. Running ps1 scripts and wrapped ps1 script in a loop but the memory usage is stable.

Could you try to pin this issue (if it still occurs) to a specific check? That would be helpful.

**Comment by FranckSallet** [comment]
after analysis, I see that the memory leak is located on the default checks
I use the check_tasksched via an alias and each time this check is used, the memory increases

**Comment by lgmu** [comment]
Thanks, I'll try to reproduce it when I find time for it

**Comment by pyves007** [comment]
Hello, and thanks to @FranckSallet , i was testing each checks separately also, i have arrived at the same conclusion, i can also said that only the check check_tasksched is producing memory leak. 
![image](https://github.com/user-attachments/assets/ae867b2e-04d8-4f2f-ab89-4ec871616e1a)

**Comment by lgmu** [comment]
Thanks for the input, I can reproduce this with 0.26 - we will fix it

**Comment by lgmu** [comment]
Issue might be [here](https://github.com/capnspacehook/taskmaster/issues/32)

**Comment by sni** [comment]
should be fine now, i replaced the 3rd party module with a powershell script. This makes retrieving scheduled tasks a bit slower, but memory was stable in my tests so far.

**Comment by lgmu** [comment]
@FranckSallet @pyves007 Is the issue resolved for you guys?

**Comment by pyves007** [comment]
@lgmu Hello, we are not using anymore the Task Scheduler check so no more memory issue from our side.
